// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v7.34.1
// source: internal/ingestion/ingestionstats/schema/stat_row.proto

package schema

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatRow is the wire format on Kafka for the ingestion usage meter. One record
// == one (tenant, hour, signal, service, environment) bucket bound for
// optikk.ingestion_stats. record_count is rows for logs/spans and datapoints
// for metrics; byte_count is uncompressed OTLP wire bytes of the resource block.
type StatRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId    uint32 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Fingerprint uint64 `protobuf:"varint,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	BucketUnix  int64  `protobuf:"varint,3,opt,name=bucket_unix,json=bucketUnix,proto3" json:"bucket_unix,omitempty"`
	Signal      string `protobuf:"bytes,4,opt,name=signal,proto3" json:"signal,omitempty"`
	Service     string `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	Environment string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	RecordCount uint64 `protobuf:"varint,7,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	ByteCount   uint64 `protobuf:"varint,8,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
}

func (x *StatRow) Reset() {
	*x = StatRow{}
	mi := &file_internal_ingestion_ingestionstats_schema_stat_row_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRow) ProtoMessage() {}

func (x *StatRow) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ingestion_ingestionstats_schema_stat_row_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRow.ProtoReflect.Descriptor instead.
func (*StatRow) Descriptor() ([]byte, []int) {
	return file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDescGZIP(), []int{0}
}

func (x *StatRow) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *StatRow) GetFingerprint() uint64 {
	if x != nil {
		return x.Fingerprint
	}
	return 0
}

func (x *StatRow) GetBucketUnix() int64 {
	if x != nil {
		return x.BucketUnix
	}
	return 0
}

func (x *StatRow) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *StatRow) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StatRow) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *StatRow) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *StatRow) GetByteCount() uint64 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

var File_internal_ingestion_ingestionstats_schema_stat_row_proto protoreflect.FileDescriptor

var file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDesc = []byte{
	0x0a, 0x37, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x5f,
	0x72, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x6f, 0x70, 0x74, 0x69, 0x6b,
	0x6b, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xff, 0x01, 0x0a, 0x07, 0x53,
	0x74, 0x61, 0x74, 0x52, 0x6f, 0x77, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f,
	0x75, 0x6e, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x79, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x62, 0x79, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x4e, 0x5a, 0x4c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6b,
	0x6b, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x3b, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDescOnce sync.Once
	file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDescData = file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDesc
)

func file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDescGZIP() []byte {
	file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDescOnce.Do(func() {
		file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDescData)
	})
	return file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDescData
}

var file_internal_ingestion_ingestionstats_schema_stat_row_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_ingestion_ingestionstats_schema_stat_row_proto_goTypes = []any{
	(*StatRow)(nil), // 0: optikk.ingest.ingestionstats.v1.StatRow
}
var file_internal_ingestion_ingestionstats_schema_stat_row_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_ingestion_ingestionstats_schema_stat_row_proto_init() }
func file_internal_ingestion_ingestionstats_schema_stat_row_proto_init() {
	if File_internal_ingestion_ingestionstats_schema_stat_row_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_ingestion_ingestionstats_schema_stat_row_proto_goTypes,
		DependencyIndexes: file_internal_ingestion_ingestionstats_schema_stat_row_proto_depIdxs,
		MessageInfos:      file_internal_ingestion_ingestionstats_schema_stat_row_proto_msgTypes,
	}.Build()
	File_internal_ingestion_ingestionstats_schema_stat_row_proto = out.File
	file_internal_ingestion_ingestionstats_schema_stat_row_proto_rawDesc = nil
	file_internal_ingestion_ingestionstats_schema_stat_row_proto_goTypes = nil
	file_internal_ingestion_ingestionstats_schema_stat_row_proto_depIdxs = nil
}
