// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metric_row.proto

package schema

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)

	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint32                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Temporality   string                 `protobuf:"bytes,4,opt,name=temporality,proto3" json:"temporality,omitempty"`
	Fingerprint   uint64                 `protobuf:"varint,8,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,9,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Value         float64                `protobuf:"fixed64,10,opt,name=value,proto3" json:"value,omitempty"`
	HistSum       float64                `protobuf:"fixed64,11,opt,name=hist_sum,json=histSum,proto3" json:"hist_sum,omitempty"`
	HistCount     uint64                 `protobuf:"varint,12,opt,name=hist_count,json=histCount,proto3" json:"hist_count,omitempty"`
	HistBuckets   []float64              `protobuf:"fixed64,13,rep,packed,name=hist_buckets,json=histBuckets,proto3" json:"hist_buckets,omitempty"`
	HistCounts    []uint64               `protobuf:"varint,14,rep,packed,name=hist_counts,json=histCounts,proto3" json:"hist_counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_metric_row_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_metric_row_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*Row) Descriptor() ([]byte, []int) {
	return file_metric_row_proto_rawDescGZIP(), []int{0}
}

func (x *Row) GetTeamId() uint32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *Row) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Row) GetTemporality() string {
	if x != nil {
		return x.Temporality
	}
	return ""
}

func (x *Row) GetFingerprint() uint64 {
	if x != nil {
		return x.Fingerprint
	}
	return 0
}

func (x *Row) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Row) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Row) GetHistSum() float64 {
	if x != nil {
		return x.HistSum
	}
	return 0
}

func (x *Row) GetHistCount() uint64 {
	if x != nil {
		return x.HistCount
	}
	return 0
}

func (x *Row) GetHistBuckets() []float64 {
	if x != nil {
		return x.HistBuckets
	}
	return nil
}

func (x *Row) GetHistCounts() []uint64 {
	if x != nil {
		return x.HistCounts
	}
	return nil
}

var File_metric_row_proto protoreflect.FileDescriptor

const file_metric_row_proto_rawDesc = "" +
	"\n" +
	"\x10metric_row.proto\x12\x18optikk.ingest.metrics.v1\"\xca\x04\n" +
	"\x03Row\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\rR\x06teamId\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12 \n" +
	"\vtemporality\x18\x04 \x01(\tR\vtemporality\x12 \n" +
	"\vfingerprint\x18\b \x01(\x04R\vfingerprint\x12!\n" +
	"\ftimestamp_ns\x18\t \x01(\x03R\vtimestampNs\x12\x14\n" +
	"\x05value\x18\n" +
	" \x01(\x01R\x05value\x12\x19\n" +
	"\bhist_sum\x18\v \x01(\x01R\ahistSum\x12\x1d\n" +
	"\n" +
	"hist_count\x18\f \x01(\x04R\thistCount\x12!\n" +
	"\fhist_buckets\x18\r \x03(\x01R\vhistBuckets\x12\x1f\n" +
	"\vhist_counts\x18\x0e \x03(\x04R\n" +
	"histCountsJ\x04\b\x03\x10\x04J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11J\x04\b\x11\x10\x12J\x04\b\x14\x10\x15J\x04\b\x15\x10\x16J\x04\b\x16\x10\x17J\x04\b\x17\x10\x18J\x04\b\x18\x10\x19J\x04\b\x19\x10\x1aJ\x04\b\x1a\x10\x1bJ\x04\b\x1b\x10\x1cR\vmetric_typeR\fis_monotonicR\x04unitR\vdescriptionR\bresourceR\n" +
	"attributesR\x16ts_bucket_hour_secondsR\aserviceR\x04hostR\venvironmentR\rk8s_namespaceR\vhttp_methodR\x10http_status_codeR\x03podR\tcontainerBOZMgithub.com/Optikk-Org/optikk-backend/internal/ingestion/metrics/schema;schemab\x06proto3"

var (
	file_metric_row_proto_rawDescOnce sync.Once
	file_metric_row_proto_rawDescData []byte
)

func file_metric_row_proto_rawDescGZIP() []byte {
	file_metric_row_proto_rawDescOnce.Do(func() {
		file_metric_row_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metric_row_proto_rawDesc), len(file_metric_row_proto_rawDesc)))
	})
	return file_metric_row_proto_rawDescData
}

var file_metric_row_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metric_row_proto_goTypes = []any{
	(*Row)(nil),
}
var file_metric_row_proto_depIdxs = []int32{
	0,
	0,
	0,
	0,
	0,
}

func init() { file_metric_row_proto_init() }
func file_metric_row_proto_init() {
	if File_metric_row_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metric_row_proto_rawDesc), len(file_metric_row_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metric_row_proto_goTypes,
		DependencyIndexes: file_metric_row_proto_depIdxs,
		MessageInfos:      file_metric_row_proto_msgTypes,
	}.Build()
	File_metric_row_proto = out.File
	file_metric_row_proto_goTypes = nil
	file_metric_row_proto_depIdxs = nil
}
