// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v7.34.1
// source: internal/ingestion/logsresource/schema/resource_row.proto

package schema

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceRow is the wire format on Kafka for logs resource metadata.
// One record == one unique resource fingerprint bound for optikk.logs_resource.
type ResourceRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId    uint32 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Fingerprint uint64 `protobuf:"varint,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Service     string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Host        string `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Pod         string `protobuf:"bytes,5,opt,name=pod,proto3" json:"pod,omitempty"`
	Environment string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	Container   string `protobuf:"bytes,7,opt,name=container,proto3" json:"container,omitempty"`
	TsBucket    uint32 `protobuf:"varint,8,opt,name=ts_bucket,json=tsBucket,proto3" json:"ts_bucket,omitempty"`
}

func (x *ResourceRow) Reset() {
	*x = ResourceRow{}
	mi := &file_internal_ingestion_logsresource_schema_resource_row_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRow) ProtoMessage() {}

func (x *ResourceRow) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ingestion_logsresource_schema_resource_row_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRow.ProtoReflect.Descriptor instead.
func (*ResourceRow) Descriptor() ([]byte, []int) {
	return file_internal_ingestion_logsresource_schema_resource_row_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRow) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ResourceRow) GetFingerprint() uint64 {
	if x != nil {
		return x.Fingerprint
	}
	return 0
}

func (x *ResourceRow) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ResourceRow) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ResourceRow) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *ResourceRow) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ResourceRow) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ResourceRow) GetTsBucket() uint32 {
	if x != nil {
		return x.TsBucket
	}
	return 0
}

var File_internal_ingestion_logsresource_schema_resource_row_proto protoreflect.FileDescriptor

var file_internal_ingestion_logsresource_schema_resource_row_proto_rawDesc = []byte{
	0x0a, 0x39, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x72, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x6f, 0x70, 0x74,
	0x69, 0x6b, 0x6b, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0xe9, 0x01, 0x0a, 0x0b, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x6f, 0x77, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x66, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x6f, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x73, 0x5f,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x73,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6b, 0x6b, 0x6c, 0x61, 0x62, 0x73, 0x2f,
	0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x3b, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_ingestion_logsresource_schema_resource_row_proto_rawDescOnce sync.Once
	file_internal_ingestion_logsresource_schema_resource_row_proto_rawDescData = file_internal_ingestion_logsresource_schema_resource_row_proto_rawDesc
)

func file_internal_ingestion_logsresource_schema_resource_row_proto_rawDescGZIP() []byte {
	file_internal_ingestion_logsresource_schema_resource_row_proto_rawDescOnce.Do(func() {
		file_internal_ingestion_logsresource_schema_resource_row_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_ingestion_logsresource_schema_resource_row_proto_rawDescData)
	})
	return file_internal_ingestion_logsresource_schema_resource_row_proto_rawDescData
}

var file_internal_ingestion_logsresource_schema_resource_row_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_ingestion_logsresource_schema_resource_row_proto_goTypes = []any{
	(*ResourceRow)(nil), // 0: optikk.ingest.logsresource.v1.ResourceRow
}
var file_internal_ingestion_logsresource_schema_resource_row_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_ingestion_logsresource_schema_resource_row_proto_init() }
func file_internal_ingestion_logsresource_schema_resource_row_proto_init() {
	if File_internal_ingestion_logsresource_schema_resource_row_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_ingestion_logsresource_schema_resource_row_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_ingestion_logsresource_schema_resource_row_proto_goTypes,
		DependencyIndexes: file_internal_ingestion_logsresource_schema_resource_row_proto_depIdxs,
		MessageInfos:      file_internal_ingestion_logsresource_schema_resource_row_proto_msgTypes,
	}.Build()
	File_internal_ingestion_logsresource_schema_resource_row_proto = out.File
	file_internal_ingestion_logsresource_schema_resource_row_proto_rawDesc = nil
	file_internal_ingestion_logsresource_schema_resource_row_proto_goTypes = nil
	file_internal_ingestion_logsresource_schema_resource_row_proto_depIdxs = nil
}
