// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: series_row.proto

package schema

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)

	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeriesRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint32                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Fingerprint   uint64                 `protobuf:"varint,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	MetricName    string                 `protobuf:"bytes,4,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	MetricType    string                 `protobuf:"bytes,5,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	Temporality   string                 `protobuf:"bytes,6,opt,name=temporality,proto3" json:"temporality,omitempty"`
	IsMonotonic   bool                   `protobuf:"varint,7,opt,name=is_monotonic,json=isMonotonic,proto3" json:"is_monotonic,omitempty"`
	Unit          string                 `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Service       string                 `protobuf:"bytes,10,opt,name=service,proto3" json:"service,omitempty"`
	Host          string                 `protobuf:"bytes,11,opt,name=host,proto3" json:"host,omitempty"`
	Environment   string                 `protobuf:"bytes,12,opt,name=environment,proto3" json:"environment,omitempty"`
	K8SNamespace  string                 `protobuf:"bytes,13,opt,name=k8s_namespace,json=k8sNamespace,proto3" json:"k8s_namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,14,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,15,opt,name=container,proto3" json:"container,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,16,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesRow) Reset() {
	*x = SeriesRow{}
	mi := &file_series_row_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesRow) ProtoMessage() {}

func (x *SeriesRow) ProtoReflect() protoreflect.Message {
	mi := &file_series_row_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*SeriesRow) Descriptor() ([]byte, []int) {
	return file_series_row_proto_rawDescGZIP(), []int{0}
}

func (x *SeriesRow) GetTeamId() uint32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *SeriesRow) GetFingerprint() uint64 {
	if x != nil {
		return x.Fingerprint
	}
	return 0
}

func (x *SeriesRow) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *SeriesRow) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *SeriesRow) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *SeriesRow) GetTemporality() string {
	if x != nil {
		return x.Temporality
	}
	return ""
}

func (x *SeriesRow) GetIsMonotonic() bool {
	if x != nil {
		return x.IsMonotonic
	}
	return false
}

func (x *SeriesRow) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *SeriesRow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SeriesRow) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SeriesRow) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SeriesRow) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *SeriesRow) GetK8SNamespace() string {
	if x != nil {
		return x.K8SNamespace
	}
	return ""
}

func (x *SeriesRow) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *SeriesRow) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *SeriesRow) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_series_row_proto protoreflect.FileDescriptor

const file_series_row_proto_rawDesc = "" +
	"\n" +
	"\x10series_row.proto\x12\x1doptikk.ingest.metricseries.v1\"\xe4\x04\n" +
	"\tSeriesRow\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\rR\x06teamId\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\x04R\vfingerprint\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x12\x1f\n" +
	"\vmetric_name\x18\x04 \x01(\tR\n" +
	"metricName\x12\x1f\n" +
	"\vmetric_type\x18\x05 \x01(\tR\n" +
	"metricType\x12 \n" +
	"\vtemporality\x18\x06 \x01(\tR\vtemporality\x12!\n" +
	"\fis_monotonic\x18\a \x01(\bR\visMonotonic\x12\x12\n" +
	"\x04unit\x18\b \x01(\tR\x04unit\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x18\n" +
	"\aservice\x18\n" +
	" \x01(\tR\aservice\x12\x12\n" +
	"\x04host\x18\v \x01(\tR\x04host\x12 \n" +
	"\venvironment\x18\f \x01(\tR\venvironment\x12#\n" +
	"\rk8s_namespace\x18\r \x01(\tR\fk8sNamespace\x12\x10\n" +
	"\x03pod\x18\x0e \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x0f \x01(\tR\tcontainer\x12X\n" +
	"\n" +
	"attributes\x18\x10 \x03(\v28.optikk.ingest.metricseries.v1.SeriesRow.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BTZRgithub.com/Optikk-Org/optikk-backend/internal/ingestion/metricseries/schema;schemab\x06proto3"

var (
	file_series_row_proto_rawDescOnce sync.Once
	file_series_row_proto_rawDescData []byte
)

func file_series_row_proto_rawDescGZIP() []byte {
	file_series_row_proto_rawDescOnce.Do(func() {
		file_series_row_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_series_row_proto_rawDesc), len(file_series_row_proto_rawDesc)))
	})
	return file_series_row_proto_rawDescData
}

var file_series_row_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_series_row_proto_goTypes = []any{
	(*SeriesRow)(nil),
	nil,
}
var file_series_row_proto_depIdxs = []int32{
	1,
	1,
	1,
	1,
	1,
	0,
}

func init() { file_series_row_proto_init() }
func file_series_row_proto_init() {
	if File_series_row_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_series_row_proto_rawDesc), len(file_series_row_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_series_row_proto_goTypes,
		DependencyIndexes: file_series_row_proto_depIdxs,
		MessageInfos:      file_series_row_proto_msgTypes,
	}.Build()
	File_series_row_proto = out.File
	file_series_row_proto_goTypes = nil
	file_series_row_proto_depIdxs = nil
}
